// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Build will fail (failOnSecretLeak) before reaching here if env vars are missing.
// At runtime, if these are undefined, supabase-js throws "supabaseUrl is required" — fail-fast.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Service-role client REMOVED (SEC-03).
// The privileged service-role credential lives ONLY inside supabase/functions/*
// (the Deno edge runtime), where it is read via Deno.env.get(...) — never
// shipped to the client bundle. If a future Node-side script needs admin
// privileges, it should import createClient directly with process.env (NOT
// import.meta.env, which would inline the value into client builds).
